#!/usr/bin/env php
<?php declare(strict_types=1);

require file_exists(__DIR__ . '/vendor/autoload.php')
    ? __DIR__ . '/vendor/autoload.php'
    : __DIR__ . '/../../../vendor/autoload.php';


use Narration\Console\Kernel;

/**
 * Creates an new instance of the router.
 */
$router = require __DIR__ . '/config/routes/console.php';

/**
 * Capture the input from globals.
 */
$input = new Symfony\Component\Console\Input\ArgvInput();

/**
 * Dispatch the input using the router.
 */
Kernel::using($router)->dispatch($input);
